//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Contas_a_Receber = new HashSet<Contas_a_Receber>();
        }
    
        public int id_cliente { get; set; }
        public Nullable<int> RG { get; set; }
        public Nullable<int> CPF { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string nome_cliente { get; set; }
        public Nullable<int> id_endereco { get; set; }
        public Nullable<int> id_status_cliente { get; set; }
        public string email { get; set; }
        public Nullable<decimal> telefone { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual Status_Usuario_Fornecedor Status_Usuario_Fornecedor { get; set; }
        public virtual ICollection<Contas_a_Receber> Contas_a_Receber { get; set; }
    }
}
