//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contas_a_Pagar
    {
        public int id_contas_a_pagar { get; set; }
        public Nullable<int> id_fornecedor { get; set; }
        public string descricao { get; set; }
        public Nullable<double> valor_a_pagar { get; set; }
        public Nullable<double> valor_pago { get; set; }
        public Nullable<System.DateTime> data_pagamento { get; set; }
        public Nullable<System.DateTime> data_valor_pago { get; set; }
        public Nullable<double> valor_juros_pago { get; set; }
        public Nullable<double> valor_deconto_pago { get; set; }
        public string produto_contasapagar { get; set; }
        public Nullable<decimal> quantidade { get; set; }
        public Nullable<int> valor_unitario { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
    }
}
