//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            this.Contas_a_Pagar = new HashSet<Contas_a_Pagar>();
        }
    
        public int id_fornecedor { get; set; }
        public Nullable<int> id_endereco { get; set; }
        public Nullable<int> id_status_fornecedor { get; set; }
        public string razao_social_fornecedor { get; set; }
        public string email { get; set; }
        public Nullable<decimal> telefone { get; set; }
        public Nullable<decimal> cnpj { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual Status_Usuario_Fornecedor Status_Usuario_Fornecedor { get; set; }
        public virtual ICollection<Contas_a_Pagar> Contas_a_Pagar { get; set; }
    }
}
