//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class testeEntities2 : DbContext
    {
        public testeEntities2()
            : base("name=testeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Contas_a_Receber> Contas_a_Receber { get; set; }
        public DbSet<Endereco> Endereco { get; set; }
        public DbSet<Fornecedor> Fornecedor { get; set; }
        public DbSet<Status_Usuario_Fornecedor> Status_Usuario_Fornecedor { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Contas_a_Pagar> Contas_a_Pagar { get; set; }
    
        public virtual ObjectResult<pc_relatorio_inadimplente_Result> pc_relatorio_inadimplente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_relatorio_inadimplente_Result>("pc_relatorio_inadimplente");
        }
    
        public virtual ObjectResult<pc_Status_Cliente_Result> pc_Status_Cliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_Status_Cliente_Result>("pc_Status_Cliente");
        }
    
        public virtual ObjectResult<pc_Status_Fornecedor_Result> pc_Status_Fornecedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_Status_Fornecedor_Result>("pc_Status_Fornecedor");
        }
    
        public virtual ObjectResult<Status_Fornecedor_1_Result> Status_Fornecedor_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Status_Fornecedor_1_Result>("Status_Fornecedor_1");
        }
    
        public virtual ObjectResult<pc_Relatorio_inadimplente_1_Result> pc_Relatorio_inadimplente_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_Relatorio_inadimplente_1_Result>("pc_Relatorio_inadimplente_1");
        }
    
        public virtual ObjectResult<pc_relatorio_pagamento_Result> pc_relatorio_pagamento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_relatorio_pagamento_Result>("pc_relatorio_pagamento");
        }
    
        public virtual ObjectResult<pc_status_clientes_Result> pc_status_clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_status_clientes_Result>("pc_status_clientes");
        }
    
        public virtual ObjectResult<pc_status_cliente1_Result> pc_status_cliente1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_status_cliente1_Result>("pc_status_cliente1");
        }
    
        public virtual ObjectResult<pc_status_cliente2_Result> pc_status_cliente2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_status_cliente2_Result>("pc_status_cliente2");
        }
    
        public virtual ObjectResult<pc_status_cliente3_Result> pc_status_cliente3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_status_cliente3_Result>("pc_status_cliente3");
        }
    
        public virtual ObjectResult<pc_status_cliente4_Result> pc_status_cliente4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_status_cliente4_Result>("pc_status_cliente4");
        }
    
        public virtual ObjectResult<pc_status_fornecedor2_Result> pc_status_fornecedor2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_status_fornecedor2_Result>("pc_status_fornecedor2");
        }
    
        public virtual ObjectResult<pc_relatorio_pagamento1_Result> pc_relatorio_pagamento1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pc_relatorio_pagamento1_Result>("pc_relatorio_pagamento1");
        }
    }
}
