//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int id_usuario { get; set; }
        public string nome_usuario { get; set; }
        public string email_usuario { get; set; }
        public string senha { get; set; }
        public string confirmar_senha { get; set; }
        public Nullable<int> id_endereco { get; set; }
    
        public virtual Endereco Endereco { get; set; }
    }
}
